import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {validate,descriptionOf,sha256} from '../lib/parcel/contract.ts';
import {ParcelService} from '../lib/parcel/service.ts';
import {handleMcp} from '../lib/parcel/mcp.ts';
import {q,withLease} from '../lib/parcel/db.ts';
import type {Database,Statement} from '../lib/parcel/db.ts';
const catalog={ups:{name:'UPS'},fedex:{name:'FedEx'},swiship:{name:'Amazon (Third Party)'},amzlus:{name:'Amazon'},nullok:{name:'Null',extra_required:null},extra:{name:'Private',extra_required:5}};
const candidate=(i=0)=>({carrier_code:'ups',tracking_number:'1Z'+String(i).padStart(16,'0'),merchant_label:'Example Shop',item_name:'Raincoat',verified:{merchant:true,tracking:true,non_amazon_retail:true,merchant_label_only:true,requires_extra_data:false,item_summary_benign:true}});
class TestDB implements Database {
 raw=new DatabaseSync(':memory:'); failWrites=false;
 constructor(){for(const name of readdirSync(new URL('../drizzle',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())this.raw.exec(readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'))}
 prepare(sql:string):Statement {let values:unknown[]=[];const stmt={bind(...args:unknown[]){values=args;return stmt},first:async<T>()=>(this.raw.prepare(sql).get(...values as [])??null) as T|null,all:async<T>()=>({results:this.raw.prepare(sql).all(...values as []) as T[]}),run:async()=>{if(this.failWrites)throw new Error('synthetic storage failure');const result=this.raw.prepare(sql).run(...values as []);return {meta:{changes:Number(result.changes)}}}};return stmt}
 async batch(statements:Statement[]){this.raw.exec('BEGIN IMMEDIATE');try{const results=[];for(const s of statements)results.push(await s.run());this.raw.exec('COMMIT');return results}catch(e){this.raw.exec('ROLLBACK');throw e}}
}
async function setup(options:{active?:boolean,mode?:string}={}) {const db=new TestDB();const now=1800000000000;const calls:{url:string,method:string,body?:string}[]=[];const deliveries:{carrier_code:string,tracking_number:string,description?:string}[]=[];let mode=options.mode??'ok';let postHook:(()=>Promise<void>)|undefined;
 await q(db,'INSERT INTO control(id,migration_digest,verified_at) VALUES(1,?,?)',options.active===false?null:'synthetic-migration',options.active===false?null:now).run();
 const fetcher=async(url:unknown,init?:RequestInit)=>{const u=String(url),method=init?.method??'GET';calls.push({url:u,method,body:init?.body as string|undefined});assert.equal(init?.redirect,'manual');assert.equal(init?.credentials,'omit');if(u.endsWith('supported_carriers.json')){assert.equal(init?.headers,undefined);return Response.json(catalog)}
 assert.equal((init?.headers as Record<string,string>)['api-key'],'synthetic-key');
 if(method==='POST'){const body=JSON.parse(init!.body as string);const row=await q(db,'SELECT status FROM ledger WHERE pair=?',body.carrier_code+':'+body.tracking_number).first<{status:string}>();assert.equal(row?.status,'uncertain');assert.ok(await q(db,"SELECT id FROM quota WHERE kind='add'").first());if(postHook)await postHook();if(mode==='timeout')throw new Error('synthetic timeout');if(mode==='failed')return Response.json({success:false});if(mode==='malformed')return new Response('not json');if(mode!=='stale')deliveries.push(body);return Response.json({success:true});}
 if(mode==='readfailed')return new Response('no',{status:502});return Response.json({success:true,deliveries:deliveries.map(x=>({...x,extra_information:'never retained private data'}))});};
 const config={DB:db,PARCEL_API_KEY:'synthetic-key',PARCEL_WRITES_ENABLED:'true',OWNER_EMAIL_SHA256:await sha256('owner@example.test')};const service=new ParcelService(config,{fetch:fetcher as typeof fetch,now:()=>now});return {db,now,calls,deliveries,service,config,fetcher,setMode:(m:string)=>mode=m,setPostHook:(h:()=>Promise<void>)=>postHook=h};
}
test('strict source candidate schema and privacy rules',()=>{assert.equal(descriptionOf(validate(candidate(),catalog)),'Example Shop: Raincoat');for(const patch of [{email:'private'},{merchant_label:'Amazon'},{merchant_label:'Whole Foods'},{carrier_code:'extra'},{carrier_code:'unknown'},{tracking_number:'ORDER123'},{tracking_number:'TBA1234567890'},{item_name:null},{item_name:'private@example.test'},{item_name:'x'.repeat(41)}])assert.throws(()=>validate({...candidate(),...patch},catalog));const s=candidate();s.item_name='Prescription medicine';assert.equal(descriptionOf(validate(s,catalog)),'Example Shop');s.item_name='Raincoat';s.verified.item_summary_benign=false;assert.equal(descriptionOf(validate(s,catalog)),'Example Shop');assert.doesNotThrow(()=>validate({...candidate(),carrier_code:'amzlus',tracking_number:'TBA1234567890'},catalog));assert.doesNotThrow(()=>validate({...candidate(),carrier_code:'nullok'},catalog));assert.throws(()=>validate({...candidate(),verified:{...candidate().verified,tracking:1}},catalog));assert.throws(()=>validate({...candidate(),verified:{...candidate().verified,raw_email:true}},catalog));});
test('reserve before POST, exact payload, readback and duplicate protection',async()=>{const s=await setup();assert.equal((await s.service.ingest(candidate())).status,'added_and_read_verified');assert.deepEqual(JSON.parse(s.calls.find(c=>c.method==='POST')!.body!),{carrier_code:'ups',tracking_number:candidate().tracking_number,description:'Example Shop: Raincoat'});assert.equal((await s.service.ingest(candidate())).status,'skipped_duplicate_or_pending');assert.equal(s.calls.filter(c=>c.method==='POST').length,1);const st=await s.service.status();assert.equal(st.additions_last_24h,1);assert.equal(st.reads_last_hour,4);assert.ok(!JSON.stringify(s.db.raw.prepare('SELECT * FROM parcel_cache').all()).includes('never retained'));});
for(const mode of ['timeout','failed','malformed'])test(`uncertain ${mode} remains durable across restart, never retries`,async()=>{const s=await setup({mode});await assert.rejects(s.service.ingest(candidate()));const restarted=new ParcelService(s.config,{fetch:s.fetcher as typeof fetch,now:()=>s.now});assert.equal((await restarted.ingest(candidate())).status,'skipped_duplicate_or_pending');assert.equal(s.calls.filter(c=>c.method==='POST').length,1);assert.equal((await restarted.status()).additions_last_24h,1);});
test('cached readback does not falsely confirm or authorize resend',async()=>{const s=await setup({mode:'stale'});assert.equal((await s.service.ingest(candidate())).status,'submitted_pending_reconciliation');assert.equal((await s.service.ingest(candidate())).status,'skipped_duplicate_or_pending');s.deliveries.push({carrier_code:'ups',tracking_number:candidate().tracking_number,description:'Example Shop: Raincoat'});await s.service.verify();assert.equal((await q(s.db,'SELECT status FROM ledger').first<{status:string}>())?.status,'seen');});
test('concurrent same or different requests cannot write concurrently',async()=>{for(const second of [candidate(),candidate(2)]){const s=await setup();let unblock:()=>void=()=>{};let entered:()=>void=()=>{};const ready=new Promise<void>(r=>entered=r);s.setPostHook(async()=>{entered();await new Promise<void>(r=>unblock=r)});const first=s.service.ingest(candidate());await ready;await assert.rejects(s.service.ingest(second),/importer_busy/);unblock();await first;assert.equal(s.calls.filter(c=>c.method==='POST').length,1)}});
test('20 failed additions exhaust rolling daily allowance',async()=>{const s=await setup({mode:'timeout'});for(let i=0;i<20;i++)await assert.rejects(s.service.ingest(candidate(i)));await assert.rejects(s.service.ingest(candidate(21)),/daily_add_limit/);assert.equal(s.calls.filter(c=>c.method==='POST').length,20);assert.equal((await s.service.status()).additions_last_24h,20);});
test('20 read reservations include failures and block 21st',async()=>{const s=await setup({mode:'readfailed'});for(let i=0;i<10;i++)await assert.rejects(s.service.verify());await assert.rejects(s.service.verify(),/hourly_read_limit/);assert.equal((await s.service.status()).reads_last_hour,20);assert.equal(s.calls.length,10);});
test('durable lease is never stolen on elapsed time',async()=>{const s=await setup();await q(s.db,'UPDATE control SET token=?,locked_at=? WHERE id=1','crashed-owner',1).run();await assert.rejects(s.service.verify(),/importer_busy/);assert.equal(s.calls.length,0);assert.equal((await s.service.status()).recovery_required,true);});
test('storage failure prevents outbound calls',async()=>{const s=await setup();s.db.failWrites=true;await assert.rejects(s.service.ingest(candidate()));assert.equal(s.calls.filter(c=>c.method==='POST').length,0)});
test('missing key, migration and cutover gates fail before network',async()=>{const s=await setup({active:false});await assert.rejects(s.service.ingest(candidate()),/migration_or_connection/);s.config.PARCEL_API_KEY='';await assert.rejects(s.service.ingest(candidate()),/key_not_configured/);s.config.PARCEL_API_KEY='synthetic-key';s.config.PARCEL_WRITES_ENABLED='false';await assert.rejects(s.service.ingest(candidate()),/cutover_not_enabled/);assert.equal(s.calls.length,0);});
test('migration requires explicit gate; verifies pairs and exact attempt counts, idempotent',async()=>{const s=await setup({active:false});const input={seen:['fedex:123456789012'],uncertain:['fedex:123456789013'],attempts:[s.now-1000,s.now-2000],reads:[s.now-500]};await assert.rejects(s.service.importLedger(input),/migration_not_authorized/);s.config.PARCEL_WRITES_ENABLED='false';(s.config as Record<string,unknown>).PARCEL_MIGRATION_ALLOWED='true';await assert.rejects(s.service.importLedger(input),/connection_not_verified/);await s.service.verify();const result=await s.service.importLedger(input);assert.equal(result.status,'migration_verified');assert.equal((await s.service.importLedger(input)).status,'migration_already_verified');assert.equal((await s.service.status()).additions_last_24h,2);assert.equal((await s.service.status()).writes_enabled,false);assert.equal(s.calls.filter(c=>c.method==='POST').length,0);});
function request(method:string,args:unknown={},headers:Record<string,string>={}){return new Request('https://private.example/mcp',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify({jsonrpc:'2.0',id:1,method,...(method==='tools/call'?{params:args}:{})})})}
test('unauthenticated, service-only and wrong-owner calls fail closed',async()=>{const s=await setup();for(const h of [{},{'OAI-Sites-Authorization':'Bearer synthetic-service'},{'oai-authenticated-user-id':'other','oai-authenticated-user-email':'other@example.test'}]){const r=await handleMcp(request('tools/call',{name:'parcel_status',arguments:{}},h as Record<string,string>),s.config);assert.ok([401,403].includes(r.status));assert.ok(!JSON.stringify(await r.json()).includes('synthetic-key'))}assert.equal(s.calls.length,0)});
test('authorized initialization, static discovery, status; arbitrary arguments rejected',async()=>{const s=await setup();const h={'oai-authenticated-user-id':'owner-site-id','oai-authenticated-user-email':'owner@example.test'};for(const method of ['initialize','tools/list']){const r=await handleMcp(request(method,{},h),s.config);assert.equal(r.status,200);const body=JSON.stringify(await r.json());assert.ok(!body.includes('synthetic-key'));assert.ok(!body.includes('owner@example.test'));assert.ok(!body.includes('1Z000000'))}const r=await handleMcp(request('tools/call',{name:'parcel_status',arguments:{}},h),s.config);assert.equal(((await r.json()) as {result:{isError?:boolean}}).result.isError,undefined);const bad=await handleMcp(request('tools/call',{name:'parcel_status',arguments:{secret:'do not store'}},h),s.config);assert.equal(((await bad.json()) as {result:{isError?:boolean}}).result.isError,true)});
test('existing short placeholder tracking does not block refresh',async()=>{const s=await setup();s.deliveries.push({carrier_code:'pholder',tracking_number:'12345'});await s.service.verify();assert.ok(await q(s.db,'SELECT pair FROM ledger WHERE pair=?','pholder:12345').first());});
test('migration marker failure can resume identical snapshot without double quota',async()=>{const s=await setup({active:false});s.config.PARCEL_WRITES_ENABLED='false';(s.config as Record<string,unknown>).PARCEL_MIGRATION_ALLOWED='true';await s.service.verify();const original=s.db.prepare.bind(s.db);let fail=true;s.db.prepare=(sql)=>{if(sql.startsWith('UPDATE control SET migration_digest')&&fail){fail=false;throw new Error('synthetic marker failure')}return original(sql)};const snapshot={seen:['pholder:12345'],uncertain:[],attempts:[s.now],reads:[]};await assert.rejects(s.service.importLedger(snapshot));assert.equal((await s.service.status()).migration_verified,false);assert.equal((await s.service.importLedger(snapshot)).status,'migration_verified');assert.equal((await s.service.status()).additions_last_24h,1);});
