import {PARCEL_ICON_URL} from './branding';
export type Status={key_configured:boolean;writes_enabled:boolean;migration_verified:boolean;connection_verified_at:number|null;recovery_required:boolean};
function Check({label,done,value}:{label:string;done:boolean;value:string}){return <li><span className={'check '+(done?'complete':'')} aria-hidden="true">{done?'✓':''}</span><span>{label}</span><span className={'value '+(done?'complete':'')}>{value}</span></li>}

export function ImporterView({status,error,loading,refresh}:{status:Status|null;error:string;loading:boolean;refresh:()=>void}){return <main><header><img src={PARCEL_ICON_URL} referrerPolicy="no-referrer" alt="Parcel" width="64" height="64"/><h1>Parcel Gmail Importer</h1></header>
<section aria-label="Importer status"><div className="status"><div><span className={'status-dot '+(status?.writes_enabled?'enabled':'')} aria-hidden="true"/><h2>{status?.writes_enabled?'Importing enabled':status?'Importing paused':'Loading status…'}</h2></div><button onClick={refresh} disabled={loading} aria-label="Refresh status"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M16.5 7A7 7 0 1 0 17 12M16.5 2v5h-5" strokeLinecap="round" strokeLinejoin="round"/></svg>{loading?'Refreshing…':'Refresh'}</button></div>
{error?<p className="notice" role="alert">{error}{error.startsWith('Sign in')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a>}</p>:<><ol aria-label="Setup checklist"><Check label="Parcel API key" done={!!status?.key_configured} value={status?.key_configured?'Added':'Needed'}/><Check label="Parcel connection" done={!!status?.connection_verified_at} value={status?.connection_verified_at?'Verified':'Not verified'}/><Check label="Existing import history" done={!!status?.migration_verified} value={status?.migration_verified?'Verified':'Pending'}/><Check label="Cloud importing" done={!!status?.writes_enabled} value={status?.writes_enabled?'Enabled':'Paused'}/></ol>{status&&!status.key_configured&&<p className="note">Secure API key entry is still being set up.</p>}</>}
{status?.recovery_required&&<p className="notice" role="alert">An interrupted request needs review before importing can resume.</p>}
</section><footer className="app-footer"><p className="footer-title">Parcel Gmail Importer</p><p>Made by John Niedermeyer, with a little help from Codex.</p><p className="footer-help">Need help?</p><nav aria-label="Project links"><a href="https://github.com/niederme/parcel-gmail-importer/issues" target="_blank" rel="noopener noreferrer">GitHub Issues</a><span aria-hidden="true">·</span><a href="https://nieder.me/" target="_blank" rel="noopener noreferrer">nieder.me</a></nav></footer></main>}
